/**
 * Generates WebP siblings + blur placeholder map for Next.js Image.
 * Usage: node scripts/optimize-images.mjs
 */
import fs from "fs";
import path from "path";
import sharp from "sharp";

const ROOT = path.resolve("public/images");
const OUT_BLURS = path.resolve("src/lib/image-blurs.ts");

const blurs = {};

async function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full);
      continue;
    }
    const ext = path.extname(entry.name).toLowerCase();
    if (![".jpg", ".jpeg", ".png"].includes(ext)) continue;

    const webpPath = full.replace(/\.(jpe?g|png)$/i, ".webp");
    await sharp(full).webp({ quality: 82 }).toFile(webpPath);

    const thumb = await sharp(full).resize(12, 12, { fit: "inside" }).webp({ quality: 40 }).toBuffer();
    const publicPath =
      "/" + path.relative("public", webpPath).split(path.sep).join("/");
    blurs[publicPath] = `data:image/webp;base64,${thumb.toString("base64")}`;

    console.log("webp:", publicPath);
  }
}

await walk(ROOT);

const file = `/** Auto-generated by scripts/optimize-images.mjs — do not edit by hand */\nexport const IMAGE_BLUR_DATA: Record<string, string> = ${JSON.stringify(blurs, null, 2)} as const;\n\nexport function blurDataFor(src: string): string | undefined {\n  const webp = src.replace(/\\.(jpe?g|png)$/i, ".webp");\n  return IMAGE_BLUR_DATA[webp] ?? IMAGE_BLUR_DATA[src];\n}\n`;

fs.writeFileSync(OUT_BLURS, file);
console.log("Wrote", OUT_BLURS, Object.keys(blurs).length, "blur entries");
