/** Auto-generated by scripts/optimize-images.mjs — do not edit by hand */
export const IMAGE_BLUR_DATA: Record<string, string> = {
  "/images/ancient_manuscript.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAwAA4BaJZACdAELM4myH44A/k00geO07+ZgbOPQM4QYBUtA5Tave48fq0UPBGI5uJeOsEDfjQTiUXvgR5FnSm81Dst7lol3LZaD0AA=",
  "/images/badges/asset12.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMAAwAA4BaJZQAD4fwc80Ma+QAAP7h7BtIl2IOOTslxfJXQh9+OKXH4G7tN+kUx9X5f9S1Jv5MDdhBU402mtUmILH3/nCeORfqE07sAAA=",
  "/images/bg/asset3.webp": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoJAAwAA4BaJQBOgBtiDPAAAM4panmwEuHDyU3H5t4bfu8JoGNTvTR2UzC9ibegDzCyDOiUbnrfZuZNM0kbM5onYuE1QJ22LgAAAA==",
  "/images/bibhitaki.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMAAoAA4BaJYgCdAECpsqFPdojAAD+9R5BryNkSUtKcoJOnrbjx4gciKiLXW+Fgumlw/k0q2+xcBJ+pEjXeNwfVTMMTpgVHdMHCnEDwNWMw6DP49l/wAAA",
  "/images/combos/1 product-13.jpg_202605240444.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoMAAwAA4BaJZwAAxYTt8uow7AAAP74GX3C8jyuxdn7kGeHsH+AUtLh6Dq3dAEeMJFQTzgQAAA=",
  "/images/combos/2 product_render_202605240445.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoMAAwAA4BaJZQAAujUuHyAAP7uW6o448uhggZ1KLozoE0v8tcu1Oh+atGVCAkxILyxbn7eBGdbK/Scjf/Xxh13i4AAAA==",
  "/images/combos/3 product 202605240445.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoMAAwAA4BaJZwAAfY475bAAP7ifZRIAmVdqkHIfHyBDyqfHer4brze1Fc4jsXngrnzOkBTYrdAo8aQnQUk6bl7XZkxGz/jrgQUQgAA",
  "/images/herbs/Haridra_fresh_plant_on_cream_202605240058.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAgCdASoMAAwAA4BaJagCdAYtV2ayqO7lxAAA/uihxTq2THBhKMxL80Dp+7Z5e5ucuLTLIXBxu6hYc8sXQFcvPiJ+TQ6cT/5CV1IqXVE9rgAA",
  "/images/herbs/kantakari.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAwAA4BaJQAB8SIvOg9+YAAA/vVZvZKurkNtqkd63Z6Fa5LvXes8A14rGu2IrpFK6O3wxWkPHahdVyemA6+lwXvbsS377NkJUAAA",
  "/images/herbs/mulethi.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoMAAwAA4BaJZgCdAYq/q15JF8qAAD+9N/Z3tcp/3NoVIwgqsus75P2XM/ud+aSrKgjL3s4Isih7vV5/LyzNQh0UxBThHmhVSgHTNStOw5NRMlsn9mAAA==",
  "/images/herbs/pippali.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoMAAwAA4BaJYgCdAD0sqrYWbKmAAD+9xFrcykVBZYIfNtik0A9hFze/jgTacevON3y85Xa3pptmbe+vTEmryTvi5Jum58jw7rTAvpAAAA=",
  "/images/herbs/pushkarmool.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoMAAwAA4BaJZQCw7Ystgf3nuBvAIAA/vfwGsTJjkV9z3Vdd7dYTDXm8ddFoPIyAamB7bloZkn79L5JmxpfuG9c1IIGkxu4NHMIceMAAAA=",
  "/images/herbs/tulsi.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoMAAwAA4BaJQAB8fnF4oyOuIAA/vc+JNsjPIqkb9L44uT5K2Q5YZVKuGb+WJfJ1MKgPstD6JormKUnOU0fgkx/jr7xT8SClFz+TNAA",
  "/images/herbs/vasaka.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoMAAwAA4BaJaACdAYwTjInE1jKAAD+9R40CP8w1ZjVQiPTaJk4B/+03FVJcf6FpjykoPuN6akL09Ejl6gQ0L9E8H0hp8xNfifjpSeaHbh2AAAA",
  "/images/hero/asset1-hero-product.webp": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoJAAwAA4BaJZACdAD0L5S+AAD+15TzgXLQazqxo9xmemenvYpDzOC/Zd+oRwIVxu5xg9p9553qyRT/jERTcmrheDQLIFvZDhIAAA==",
  "/images/hero/asset2.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoMAAcAA4BaJZQAAudP3WAA/uoBOm+Px6Qe2qcVnNHBiLeLgAA=",
  "/images/hitesh.webp": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoIAAwAA4BaJZQCsADzfQ4DIAD+3/O/V/lyemdWv3HW4gIPRmRGwhUf+ydPTJ7zJWYzEdSByOMUllga90y2IFxkGzY3PpIeW2AAAA==",
  "/images/jaideep singh.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoJAAwAA4BaJYwC7AD6IkYTQaAA9nXv3FTvwHjpTD9Zs7iJ3ZISIZYCB7etwgccBZa6wfqo6QAAAA==",
  "/images/logo/Royalswag_LOGO01.webp": "data:image/webp;base64,UklGRogAAABXRUJQVlA4WAoAAAAQAAAACwAABAAAQUxQSD0AAAAAAwBcGwACDgsVFAwNAA68TAAEW2FgUmVNMX9/jE0TWWRaVltEXHeOgnAeTltgZ1sjJHJndE8AFxwXISELAFZQOCAkAAAAsAEAnQEqDAAFAAOAWiUAToAh38BdgAD+9gIHqSBGKGqlAAAA",
  "/images/lungs-after.webp": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoMAAwAA4BaJagCdADdpuCiH0lAAP718LyCUDSSB7EYf55p06eH0UHymS0yWstq5NGNS9qSdCE9MLOeSr/ckiIcSYBTjEffV1PdagYQFejZcj8AOAA=",
  "/images/lungs-before.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAwAA4BaJZQCdAELXPrzJgAA/vfHNJUJWuRacQpI6AQfE8AwWlEQIRV/lYAA",
  "/images/lungtest .webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAcAA4BaJZwAAtzfNZMAAP60K+y3jkKkzchsBMHuD8LQRhdPqWvP7JpPCVpM8dJKlKfXkzXiQIAA",
  "/images/lungtest.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAcAA4BaJZwAAtzfNZMAAP60K+y3jkKkzchsBMHuD8LQRhdPqWvP7JpPCVpM8dJKlKfXkzXiQIAA",
  "/images/manoj.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoJAAwAA4BaJYgCdAD0uc8TtCAA/njpmwc7+2+E0gvIlDTKNzhJ++FuMINE5Zx0SAm0BE5ZHsUdAen5WCa4fpAA",
  "/images/product/product-1.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAwAA4BaJZgCdAEO+XodXTUAAP7v0bOQ39ugkKG40KSxpox/IzNbkdbdxquK28sJuXhfhfGZwfXC2uUk9RgA",
  "/images/product/product-10.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoMAAwAA4BaJaQAAtzR3/BwAAD+9/l4KZrXV/J9zs9N1xQeiettckO7n2zIJPn4AAAAAA==",
  "/images/product/product-11.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAwAA4BaJYwAAlw4KH5sAAD++LpvbM2VXKIyzBJj+Iw1olwf+iW2JL1fZv+AO2Yfqyfp6Sj490WXSbAUsAAA",
  "/images/product/product-13.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoMAAwAA4BaJZwAAxYTt8uow7AAAP74GX3C8jyuxdn7kGeHsH+AUtLh6Dq3dAEeMJFQTzgQAAA=",
  "/images/product/product-4.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAwAA4BaJaQAAtz3cWioAAD+91wzzHKmZO3tcsi30h4bKn8InBdm1ztuNNEAAAA=",
  "/images/product/product-5.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoMAAwAA4BaJbACdAEPCPkQtuAA/scsXe3MkdigI9xcgZ+Tgz7K8oGV3Y/qyQnidsUlW+WiupGKnKjouZYVjfaNL0NEnZsMLYeUASzrN3fYAAAA",
  "/images/product/product-7.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAwAA4BaJaQAAujdnxHXgAD+90ITSHaclfWPl7cO7tnELKc7AAAA",
  "/images/product/product-8.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAABQAQCdASoMAAwAA4BaJQBOgCgAAP7wFjzWpUkC3WGoOemtxiw8NCMoAAA="
} as const;

export function blurDataFor(src: string): string | undefined {
  const webp = src.replace(/\.(jpe?g|png)$/i, ".webp");
  return IMAGE_BLUR_DATA[webp] ?? IMAGE_BLUR_DATA[src];
}
